Manage Deck - PMS/Controllers/ProjectsController.cs
using Manage_Deck___PMS.Data;
using Manage_Deck___PMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Manage_Deck___PMS.Controllers
{
    [Authorize(Roles = "Admin,User")]
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProjectsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
           // HttpContext.Session.se.SetString("name", "Jignesh Trivedi");
            HttpContext.Session.SetString("name", "aaa");
            return View(await _context.Project.ToListAsync());
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            HttpContext.Session.SetString("name", "aaa");
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.ProjectId == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProjectId,ProjectName,ProjectDescription,CreatedTime")] Project project)
        {
            if (ModelState.IsValid)
            {
                project.ProjectId = Guid.NewGuid();
                project.CreatedTime = DateTime.Now;
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ProjectId,ProjectName,ProjectDescription,CreatedTime")] Project project)
        {
            if (id != project.ProjectId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ProjectId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Project
                .FirstOrDefaultAsync(m => m.ProjectId == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var project = await _context.Project.FindAsync(id);
            _context.Project.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(Guid id)
        {
            return _context.Project.Any(e => e.ProjectId == id);
        }

        [HttpGet("Projects/{name}/Tasks")]
        public IActionResult GetProjectTasks(string name)
        {
            var id = ProjectByName(name);

            var Tasks = _context.Task.Where(t => t.ProjectId == id).OrderByDescending(t => t.TaskName).ToList();
            
            ViewBag.tasks = Tasks;
            
            return View();
        }

        private Guid ProjectByName(string projectName)
        {
            try
            {
                var project = _context.Project.First(p => p.ProjectName == projectName);

                return project.ProjectId;

            }
            catch (InvalidOperationException ioe)
            {
                Console.WriteLine("No Project with that name found!\n ------------------------ \n" + ioe);

                return Guid.Empty;
            }
        }
    }
}

Manage Deck - PMS/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Manage_Deck___PMS.Controllers
{
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }
        [Authorize(Roles = "Admin, User")]
        public IActionResult Index()
        {
            var roles = roleManager.Roles.ToList();
            return View(roles);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View(new IdentityRole());
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            await roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
    }
}

Manage Deck - PMS/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Manage_Deck___PMS.Data;
using Manage_Deck___PMS.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Manage_Deck___PMS.Controllers
{
    public class TasksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;


        public TasksController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Tasks
        [Authorize(Roles = "Admin,User")]
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["CurrentFilter"] = searchString;

            var tasks = from c in _context.Task
                             select c;
            if (!String.IsNullOrEmpty(searchString))
            {
                tasks = tasks.Where(c => c.TaskName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    tasks = tasks.OrderByDescending(c => c.TaskName);
                    break;
                case "Date":
                    tasks = tasks.OrderBy(c => c.DueDate);
                    break;
                case "date_desc":
                    tasks = tasks.OrderByDescending(c => c.DueDate);
                    break;
                default:
                    tasks = tasks.OrderBy(c => c.TaskName);
                break;
            }
            return View(await tasks.AsNoTracking().ToListAsync());

            
        }

        // GET: Tasks/Details/5
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Task
                .FirstOrDefaultAsync(m => m.Id == id);
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        // GET: Tasks/Create
        [Authorize(Roles = "User")]
        public IActionResult Create()
        {
            var Projects = _context.Project.ToList();

            ViewBag.Projects = Projects;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Create([Bind("Id,TaskName,TaskDescription,Label,DueDate,Completed,Assignee,Reporter,ProjectId")] Models.Task task)
        {
            if (ModelState.IsValid)
            {
                task.Id = Guid.NewGuid();
                _context.Add(task);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(task);
        }

        // GET: Tasks/Edit/5
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Task.FindAsync(id);
            if (task == null)
            {
                return NotFound();
            }
            return View(task);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,TaskName,TaskDescription,Label,DueDate,Completed,Assignee,Reporter,ProjectId")] Models.Task task)
        {
            if (id != task.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(task);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskExists(task.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(task);
        }

        // GET: Tasks/Delete/5
        [Authorize(Roles = "User")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Task
                .FirstOrDefaultAsync(m => m.Id == id);
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        // POST: Tasks/Delete/5
        [Authorize(Roles = "User")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var task = await _context.Task.FindAsync(id);
            _context.Task.Remove(task);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TaskExists(Guid id)
        {
            return _context.Task.Any(e => e.Id == id);
        }
    }
}

Manage Deck - PMS/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" href="favicon.ico" type="image/x-icon" />

    <title>@ViewData["Title"] - Manage Deck</title>

    <!-- Bootstrap Core and vandor -->
    <script src="https://use.fontawesome.com/76aea54f66.js"></script>
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
    <link rel="stylesheet" href="~/theme/assets/plugins/bootstrap/css/bootstrap.min.css" />

    <!-- Plugins css -->
    <link rel="stylesheet" href="~/theme/assets/plugins/charts-c3/c3.min.css" />

    <!-- Core css -->
    <link rel="stylesheet" href="~/theme/assets/css/main.css" />
    <link rel="stylesheet" href="~/theme/assets/css/theme1.css" />
</head>

<body class="font-montserrat sidebar_dark">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
        </div>
    </div>

    <div id="main_content">

        <div id="header_top" class="header_top dark">
            <div class="container">
                <div class="hleft">
                    <a class="header-brand" asp-controller="Home" asp-action="Index"><i class="fa fa-soccer-ball-o brand-logo"></i></a>
                    <div class="dropdown">
                        <a class="nav-link icon" asp-controller="Projects" asp-action="Index"><i class="fa fa-dashboard"></i></a>
                        <a class="nav-link icon" asp-controller="Tasks" asp-action="Index"><i class="fa fa-list-ol"></i></a>
                        <a class="nav-link icon" asp-controller="Role" asp-action="Index"><i class="fa fa-user"></i></a>
                        <a class="nav-link icon" asp-controller="Checklists" asp-action="Index"><i class="fa fa-check-square-o"></i></a>
                    </div>
                </div>
               
            </div>
        </div>

        <div class="page" style="left: 60px; width: calc(100% - 60px)">
            <div id="page_top" class="section-body top_dark">
                <div class="container-fluid">
                    <div class="page-header">
                        <div class="left">
                            <h1 class="page-title">ManageDeck</h1>
                        </div>
                        <div class="right">
                            @*<div class="input-icon xs-hide mr-4">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-icon-addon"><i class="fa fa-search"></i></span>
                        </div>*@
                            <div class="notification d-flex">
                                <div class="dropdown d-flex">
                                    <a class="nav-link icon d-none d-md-flex btn btn-default btn-icon ml-2" data-toggle="dropdown"><i class="fa fa-user"></i></a>
                                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                        <partial name="_LoginPartial" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            @* Header END *@

            @RenderBody()

            @* Footer START *@

            <div class="section-body">
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <a href="templateshub.net">Manage Deck</a>
                            </div>
                            <div class="col-md-6 col-sm-12 text-md-right">
                                <ul class="list-inline mb-0">
                                    <li class="list-inline-item"><a href="doc/index.html">Documentation</a></li>
                                    <li class="list-inline-item"><a href="javascript:void(0)">FAQ</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>

        </div>
    </div>


    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@

    <script src="~/theme/assets/bundles/lib.vendor.bundle.js"></script>

    <script src="~/theme/assets/bundles/apexcharts.bundle.js"></script>
    <script src="~/theme/assets/bundles/counterup.bundle.js"></script>
    <script src="~/theme/assets/bundles/knobjs.bundle.js"></script>
    <script src="~/theme/assets/bundles/c3.bundle.js"></script>

    <script src="~/theme/assets/js/core.js"></script>
    <script src="~/theme/assets/js/page/project-index.js"></script>

    @RenderSection("Scripts", required: false)
</body>

</html>

Manage Deck - PMS/Views/Shared/_LoginLayout.cshtml
<!doctype html>
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" href="favicon.ico" type="image/x-icon" />

    <title>@ViewData["Title"] - Manage_Deck___PMS</title>

    <!-- Bootstrap Core and vandor -->
    <script src="https://use.fontawesome.com/76aea54f66.js"></script>
    <script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
    <link rel="stylesheet" href="~/theme/assets/plugins/bootstrap/css/bootstrap.min.css" />

    <!-- Plugins css -->
    <link rel="stylesheet" href="~/theme/assets/plugins/charts-c3/c3.min.css" />

    <!-- Core css -->
    <link rel="stylesheet" href="~/theme/assets/css/main.css" />
    <link rel="stylesheet" href="~/theme/assets/css/theme1.css" />
</head>

<body class="font-montserrat">

   @RenderBody()

    <script src="~/theme/assets/bundles/lib.vendor.bundle.js"></script>

    <script src="~/theme/assets/bundles/apexcharts.bundle.js"></script>
    <script src="~/theme/assets/bundles/counterup.bundle.js"></script>
    <script src="~/theme/assets/bundles/knobjs.bundle.js"></script>
    <script src="~/theme/assets/bundles/c3.bundle.js"></script>

    <script src="~/theme/assets/js/core.js"></script>
    <script src="~/theme/assets/js/page/project-index.js"></script>

    @RenderSection("Scripts", required: false)
</body>

</html>